# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
 #   restart: always
    ports:
      - 8181:8080