version: "2.1"

services: 
 
 
    postgres:
        image: healthcheck/postgres:alpine
        ports: ["5432:5432"]
        networks: [backing-services]
        volumes: ["postgres-data:/var/lib/postgresql/data"]
        environment:
        POSTGRES_DB: db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password