version: "2"
services:
    mysqldb:
        container_name: mysql
        image: mysql/mysql-server:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_HOST=%
            - DATA_SAVE_PATH=~/mysql/docker/data
        ports:
            - 3306:3306
        volumes:
            - mysql-data-mac:/var/lib/mysql/data
    myadmin:
        container_name: myadmin
        image: phpmyadmin/phpmyadmin:latest
        links: 
            - mysqldb:mysqldb
        ports:
            - 8181:80
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - mysqldb

volumes:
  mysql-data-mac:
